### ISSUE TITLE
make_sentence_with_start() don't working

### ISSUE THREAD

**Issue by Zero-Tolerance** [jsvine/markovify#117]
It's really broken? I can use make_sentence(), but when I try to use make_sentence_with_start(), then I got errors:

Traceback (most recent call last):
  File "C:\test.py", line 12, in <module>
    string = text_model.make_sentence_with_start("Hello")
  File "c:\python\lib\site-packages\markovify\text.py", line 254, in make_sentence_with_start
    output = self.make_sentence(init_state, **kwargs)
  File "c:\python\lib\site-packages\markovify\text.py", line 197, in make_sentence
    words = prefix + self.chain.walk(init_state)
  File "c:\python\lib\site-packages\markovify\chain.py", line 118, in walk
    return list(self.gen(init_state))
  File "c:\python\lib\site-packages\markovify\chain.py", line 107, in gen
    next_word = self.move(state)
  File "c:\python\lib\site-packages\markovify\chain.py", line 93, in move
    choices, weights = zip(*self.model[state].items())
KeyError: ('___BEGIN__', 'Hello')

Code:
```
import markovify
import codecs

with codecs.open("file.txt", encoding='utf-8') as f:
    text = f.read()

# Build the model.
text_model = markovify.Text(text)

#string = text_model.make_sentence(tries=100)
string = text_model.make_sentence_with_start("Hello")
```

Markovify 0.7.2, Python 3.7.4

**Comment by jsvine** [comment]
Hi! It's a bit difficult to diagnose what's happening without seeing the original text itself. One possibility is that there is no "Hello" in the text. Another is that the text might be formatted unusually. Closing this issue for now, but feel free to reopen with a copy of "file.txt" and/or an equivalent example.
