### ISSUE TITLE
spaCy model shortcuts are deprecated

### ISSUE THREAD

**Issue by tallpauley** [jsvine/markovify#159]
The spacy example no longer works as of spaCy v3.0. Looks like a simple documentation fix:
```
>>> import spacy
>>> nlp = spacy.load("en")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/spacy/__init__.py", line 47, in load
    return util.load_model(name, disable=disable, exclude=exclude, config=config)
  File "/usr/local/lib/python3.9/site-packages/spacy/util.py", line 328, in load_model
    raise IOError(Errors.E941.format(name=name, full=OLD_MODEL_SHORTCUTS[name]))
OSError: [E941] Can't find model 'en'. It looks like you're trying to load a model from a shortcut, which is deprecated as of spaCy v3.0. To load the model, use its full name instead:

nlp = spacy.load("en_core_web_sm")

For more details on the available models, see the models directory: https://spacy.io/models. If you want to create a blank model, use spacy.blank: nlp = spacy.blank("en")
```

**Comment by jsvine** [comment]
Thanks for flagging, now fixed!
