### ISSUE TITLE
Issue with saving model to json

### ISSUE THREAD

**Issue by benedictb** [jsvine/markovify#95]
I'm using python 2.7 and when I try to save the model to json, I get the following error

UnicodeDecodeError: 'utf8' codec can't decode bytes in position 40-42: invalid continuation byte

Full traceback: 
`Traceback (most recent call last):
  File "python/markov.py", line 23, in <module>
    model_json = text_model.to_json()
  File "/usr/local/lib/python2.7/dist-packages/markovify/text.py", line 57, in to_json
    return json.dumps(self.to_dict())
  File "/usr/local/lib/python2.7/dist-packages/markovify/text.py", line 49, in to_dict
    "chain": self.chain.to_json(),
  File "/usr/local/lib/python2.7/dist-packages/markovify/chain.py", line 124, in to_json
    return json.dumps(list(self.model.items()))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 40-42: invalid continuation byte
`

**Comment by artlung** [comment]
`json.dumps()` looks like it can take parameters for `ensure_asci`i and `encoding` - worth a shot? https://docs.python.org/2.7/library/json.html#basic-usage

As I've played with markovify and was outputting strings I ran into issues with generating the strings based on a corpus with odd characters that adding `.encode('utf-8')`  worked to get around the issue of writing to a file.

**Comment by benedictb** [comment]
Oh yeah, there must be non-ascii characters in my model. I bet that's it. I'll give the encoding a shot.
